# -*- coding: utf-8 -*-
"""primenumbers2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eqEbHdjbrJr4NQuah9peB9puFFs6AQE-
"""



#Task : Print the prime numbers which are between 1 to entered limit number (n).
#You can use a nested for loop.
#Collect all these numbers into a list

n=int(input("enter anumber :"))
L=[]
for j in range(1,n+1):
    count = 0
    for i in range(1,j+1):
      if j%i==0:
       count += 1
    if not ((j==1) or (count >=3)):
     L.append(j)
print(L)